import { defineConfig } from 'vite';
import { resolve } from 'path';
import { readdirSync, existsSync, statSync } from 'fs';

const root = import.meta.dirname;

// Blog posts are generated by scripts/build-blog.mjs into resources/<slug>/
// index.html (runs in `prebuild`). Discover them so each is a build input and a
// dev trailing-slash redirect target — no need to hand-register every post.
function blogPostSlugs() {
  const dir = resolve(root, 'resources');
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(resolve(dir, d.name, 'index.html')))
    .map((d) => d.name);
}
const POST_SLUGS = blogPostSlugs();

// The content pages live at /research/, /people/, /about/ (directory + index).
// In dev, requesting the slash-less form (/people) falls through to the root
// index.html instead of the page. This plugin redirects /people -> /people/ so
// dev matches GitHub Pages, which auto-adds the trailing slash in production.
const PAGE_DIRS = ['research', 'people', 'resources', 'about', 'manybody', 'spritelab', 'magmalab', 'froggame'];
// Post pages live one level under /resources/ (e.g. /resources/useful-math-tricks).
const POST_DIRS = POST_SLUGS.map((s) => `resources/${s}`);
function trailingSlashRedirect() {
  return {
    name: 'trailing-slash-redirect',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url.split('?')[0];
        const name = url.replace(/^\//, '');
        if (PAGE_DIRS.includes(name) || POST_DIRS.includes(name)) {
          res.statusCode = 301;
          res.setHeader('Location', url + '/');
          return res.end();
        }
        next();
      });
    },
  };
}

export default defineConfig({
  base: '/',
  plugins: [trailingSlashRedirect()],
  server: {
    port: 8000,
    // Rapier ships as WASM; make sure it isn't pre-bundled in a way that breaks init.
  },
  optimizeDeps: {
    exclude: ['@dimforge/rapier3d-compat'],
  },
  build: {
    target: 'esnext',
    outDir: 'dist',
    rollupOptions: {
      input: {
        // Multi-page app: the WebGL homepage, the content pages, and the
        // frozen /manybody demo.
        main: resolve(root, 'index.html'),
        research: resolve(root, 'research/index.html'),
        people: resolve(root, 'people/index.html'),
        resources: resolve(root, 'resources/index.html'),
        about: resolve(root, 'about/index.html'),
        manybody: resolve(root, 'manybody/index.html'),
        // Unlinked builder tool for the cube sprites.
        spritelab: resolve(root, 'spritelab/index.html'),
        // Unlinked color picker for the magma planet's body tint.
        magmalab: resolve(root, 'magmalab/index.html'),
        // Dev harness for the frog game.
        froggame: resolve(root, 'froggame/index.html'),
        // Generated blog posts (scripts/build-blog.mjs -> resources/<slug>/).
        ...Object.fromEntries(
          POST_SLUGS.map((s) => [`post-${s}`, resolve(root, `resources/${s}/index.html`)])
        ),
      },
    },
  },
});
